/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database;

import static java.sql.JDBCType.FLOAT;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.*;


/**
 *
 * @author finkfa
 */
public class filmerstellen extends javax.swing.JFrame {

    databaseexecutes dbverbindung;
    /**
     * Creates new form filmerstellen
     */
    public filmerstellen() {
        initComponents();
        dbverbindung= new databaseexecutes();
        dbverbindung.DatabaseConnection();
        Fillcombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        e_filmname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        e_genre = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        e_bewertung = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        e_kommentar = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        e_filmname.setText("Wall-E");
        e_filmname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_filmnameActionPerformed(evt);
            }
        });

        jLabel1.setText("Film Name:");

        jLabel3.setText("Genre:");

        e_genre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        e_genre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_genreActionPerformed(evt);
            }
        });

        jLabel2.setText("Bewertung:");

        e_bewertung.setText("4.15");
        e_bewertung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_bewertungActionPerformed(evt);
            }
        });

        jLabel4.setText("Kommentar:");

        e_kommentar.setColumns(20);
        e_kommentar.setRows(5);
        jScrollPane1.setViewportView(e_kommentar);

        jButton1.setText("Film erstellen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addGap(48, 48, 48)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(e_genre, javax.swing.GroupLayout.Alignment.LEADING, 0, 281, Short.MAX_VALUE)
                                .addComponent(e_filmname, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(e_bewertung)))
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(e_filmname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(e_genre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(e_bewertung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        String filmname;
        filmname = e_filmname.getText();
        
        String genre;
        genre = e_genre.getSelectedItem().toString();
        
        String bewertung;
        bewertung = e_bewertung.getText();
        //Float bewertung;
        //Float.parseFloat(e_bewertung.getText());
        
        String kommentar;
        kommentar = e_kommentar.getText();
        
        
        //kontrolle
        boolean b_bewertung = bewertung.matches("^[1-9]$|(^[0-9]\\.[0-9]?[1-9]$)");
        boolean b_filmname = !e_filmname.getText().equals("");
        
        if (b_bewertung != true){
            jLabel6.setText("x.xx verwenden");
        }
        else{
            jLabel6.setText("");
        }
        
        if(!b_filmname){
            jLabel7.setText("bitte füllen");
        }
        else{
            jLabel7.setText("");
        }
        
        if (b_bewertung && b_filmname){
            
            try{
                String sql_filmname = "select titel from film where titel = '" + filmname + "'";
            
                ResultSet rs_filmname=dbverbindung.SQLQuerry(sql_filmname);
                
                //kontrolle ob film vorhanden
                if (rs_filmname.next()){
                    rs_filmname.getString("titel");
                    jLabel5.setText("Film bereits vorhanden!");
                }
                
                //eintragen in datenbank
                else{
                    String sql_insertfilm = "INSERT INTO film(titel, beschreibung) "
                + "VALUES('" + filmname + "' ,'" + kommentar + "' )";
                    
                    dbverbindung.SQLUpdate(sql_insertfilm);
                    
                    int filmid = 1;
                    int loginid = user.GetInstance().getUser_id();
                    
                    String sqlselectfilm = "SELECT film_id FROM film WHERE titel = '" + filmname + "'";
                    ResultSet rs_film=dbverbindung.SQLQuerry(sqlselectfilm);
                    
                    if (rs_film.next()){
                        filmid = rs_film.getInt("film_id");
                    }
                    
                    String sql_insertbewertung = "INSERT INTO bewertung VALUES (" + loginid + " ," + filmid + " ," + bewertung + " ,'" + kommentar + "')";
                    dbverbindung.SQLUpdate(sql_insertbewertung);
                    
                    int genreid = 1;
                    
                    String sql_selectGenreid = "SELECT genre_id FROM genre WHERE genre_name = '" + genre + "'";
                    ResultSet rs_genre=dbverbindung.SQLQuerry(sql_selectGenreid);
                    
                    if (rs_genre.next()){
                        genreid = rs_genre.getInt("genre_id");
                    }
                    
                    String sql_insertgenrefilm = "INSERT INTO genre_film VALUES(" + filmid + " , " + genreid + ")";
                    
                    
                    jLabel5.setText("anlegen erfolgreich");
                }
            } catch (Exception e) {
                Logger.getLogger(filmerstellen.class.getName()).log(Level.SEVERE, null, e);
            }
            
            
        }
        
        
        //ausgabe ok
        //jLabel5.setText(b+"");
    }                                        

    private void e_filmnameActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void e_bewertungActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void e_genreActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(filmerstellen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(filmerstellen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(filmerstellen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(filmerstellen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new filmerstellen().setVisible(true);
            }
        });
    }
    
    private void Fillcombobox(){
        try{
            String sql_combo = "select * from genre";
            
            ResultSet rs_combo=dbverbindung.SQLQuerry(sql_combo);
            e_genre.removeAllItems();
            
            while (rs_combo.next()){
                String genre = rs_combo.getString("genre_name");
                e_genre.addItem(genre);
            }
            
        }
        catch(Exception e) {
            
        }
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField e_bewertung;
    private javax.swing.JTextField e_filmname;
    private javax.swing.JComboBox e_genre;
    private javax.swing.JTextArea e_kommentar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}
